package com.project.medicalanalize.persistence.type;

public enum Country {
    UKRAINE, RUSSIA, BELARUS,POLAND, KAZAKHSTAN, TAJIKISTAN, HUNGARY, USA, MOLDOVA, GERMANY, DENMARK, CZECH_REPUBLIC,
AUSTRIA, BELGIUM,ESTONIA, SPAIN, FRANCE, FINLAND, ENGLAND, GREECE, ITALY, CROATIA
}
