cloud:
  aws:
    credentials:
      access-key: AKIAYBFMHSABG6WH4TP7
      secret-key: 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
    region:
      static: eu-central-1
    stack:
      auto: false

application:
  bucket:
    name: medicalanalize


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090