insert into doctors values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Oleg', 'Noskov','MALE');
insert into doctors values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Sergey', 'Funtusov','MALE');
insert into doctors values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Irina', 'Cventuh','FEMALE');
insert into doctors values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Pavel', 'Noskov','MALE');
insert into doctors values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Igor', 'Babakin','MALE');
insert into doctors values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Olegs', 'Noskov','MALE');
insert into doctors values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Natasha', 'Legusha','FEMALE');
insert into doctors values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Olga', 'Zvereva','FEMALE');
insert into doctors values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Oleg', 'Unicum','MALE');
insert into doctors values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Omar', 'Eps','MALE');
insert into doctors values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Sergey', 'Maltsev','MALE');
insert into doctors values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Ilona', 'Prihodko','FEMALE');
insert into doctors values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Katia', 'Sherbina','FEMALE');
insert into doctors values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Irina', 'Rastvorceva','FEMALE');
insert into doctors values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Sergey', 'Kyi','MALE');
insert into doctors values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Nikolay', 'Shevchenko','MALE');
insert into doctors values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Sergey', 'Kysil','MALE');
insert into doctors values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Iegor', 'Funtusov','MALE');
insert into doctors values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Oleg', 'Family','MALE');
insert into doctors values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Sergey', 'Noskov','MALE');


insert into patients values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Oleg', 'Noskov',0669518856,'MALE');
insert into patients values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Sergey', 'Funtusov',0669518856,'MALE');
insert into patients values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Irina', 'Cventuh',0669518856,'FEMALE');
insert into patients values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Pavel', 'Noskov',0669518851,'MALE');
insert into patients values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Igor', 'Babakin',0669518856,'MALE');
insert into patients values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Olegs', 'Noskov',0669518856,'MALE');
insert into patients values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Natasha', 'Legusha',0669518856,'FEMALE');
insert into patients values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Olga', 'Zvereva',0669518856,'FEMALE');
insert into patients values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Oleg', 'Unicum',0669518856,'MALE');
insert into patients values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Omar', 'Eps',0669518856,'MALE');
insert into patients values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Sergey', 'Maltsev',0669518856,'MALE');
insert into patients values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Ilona', 'Prihodko',0669518856,'FEMALE');
insert into patients values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Katia', 'Sherbina',0669518856,'FEMALE');
insert into patients values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Irina', 'Rastvorceva',0669518856,'FEMALE');
insert into patients values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Sergey', 'Kyi',19,'MALE');
insert into patients values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Nikolay', 'Shevchenko',0669518856,'MALE');
insert into patients values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Sergey', 'Kysil',0669518856,'MALE');
insert into patients values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Iegor', 'Funtusov',0669518856,'MALE');
insert into patients values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Oleg', 'Family',0669518856,'MALE');
insert into patients values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'Sergey', 'Noskov',0669518856,'MALE');


insert into orders values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,1,1);
insert into orders values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,2,1);
insert into orders values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,3,2);
insert into orders values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,4,3);
insert into orders values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,5,3);
insert into orders values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,6,4);
insert into orders values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,7,5);
insert into orders values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,9,6);
insert into orders values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,10,9);
insert into orders values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,11,11);
insert into orders values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,12,12);
insert into orders values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,13,13);
insert into orders values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,14,14);
insert into orders values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,15,15);
insert into orders values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,16,15);
insert into orders values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,17,17);
insert into orders values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,18,17);
insert into orders values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,19,20);
insert into orders values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true,20,20);


insert into doctor_patient values (1, 1);
insert into doctor_patient values (1, 3);
insert into doctor_patient values (1, 9);
insert into doctor_patient values (1, 15);
insert into doctor_patient values (2, 3);
insert into doctor_patient values (2, 13);
insert into doctor_patient values (2, 19);
insert into doctor_patient values (3, 4);
insert into doctor_patient values (3, 5);
insert into doctor_patient values (4, 13);
insert into doctor_patient values (4, 14);
insert into doctor_patient values (5, 5);
insert into doctor_patient values (5, 15);
insert into doctor_patient values (5, 18);
insert into doctor_patient values (5, 16);
insert into doctor_patient values (6, 7);
insert into doctor_patient values (6, 17);
insert into doctor_patient values (6, 20);
insert into doctor_patient values (7, 6);
insert into doctor_patient values (7, 12);
insert into doctor_patient values (7, 17);
insert into doctor_patient values (8, 2);
insert into doctor_patient values (8, 10);
insert into doctor_patient values (8, 20);
insert into doctor_patient values (9, 8);
insert into doctor_patient values (9, 14);
insert into doctor_patient values (9, 18);
insert into doctor_patient values (10, 8);
insert into doctor_patient values (10, 16);
insert into doctor_patient values (10, 19);